from typing import Dict, Any

def generate_itinerary_pdf(data: Dict[str, Any]) -> bytes:
    """
    Assembles itinerary details into a standard openable PDF byte stream.
    Requires no external dependencies.
    """
    dest = data.get("destination_name", "My Trip")
    days = data.get("days", 1)
    style = data.get("travel_style", "Standard")
    mode = data.get("travel_mode", "DRIVING")
    travelers = data.get("travelers", 1)
    
    # Extract budget details
    budget = data.get("budget_breakdown", {})
    total_cost = budget.get("total_cost", 0)
    fuel_cost = budget.get("fuel_cost", 0)
    acc_cost = budget.get("accommodation_cost", 0)
    food_cost = budget.get("food_cost", 0)
    tickets_cost = budget.get("entry_tickets_cost", 0)
    misc_cost = budget.get("miscellaneous_cost", 0)
    
    # Construct lines
    lines = [
        "----------------------------------------------------------------",
        f"Destination: {dest}",
        f"Trip Duration: {days} Days | Travelers: {travelers}",
        f"Travel Style: {style} | Transport Mode: {mode}",
        "----------------------------------------------------------------",
        "ESTIMATED BUDGET FORECAST:",
        f"  - Accommodation: INR {acc_cost:,.2f}",
        f"  - Food & Meals:  INR {food_cost:,.2f}",
        f"  - Fuel & Transit: INR {fuel_cost:,.2f}",
        f"  - Entry Tickets:  INR {tickets_cost:,.2f}",
        f"  - Miscellaneous: INR {misc_cost:,.2f}",
        f"  * TOTAL ESTIMATED COST: INR {total_cost:,.2f}",
        "----------------------------------------------------------------",
        "DAILY SCHEDULE DETAILS:",
    ]
    
    # Add day schedules
    schedule = data.get("day_wise_schedule", [])
    for item in schedule:
        d_num = item.get("day_number", 1)
        lines.append("")
        lines.append(f"DAY {d_num} TIMELINE:")
        
        # Add meals
        meals = item.get("meals", {})
        lines.append(f"  * Breakfast: {meals.get('breakfast', '')}")
        lines.append(f"  * Lunch:     {meals.get('lunch', '')}")
        lines.append(f"  * Dinner:    {meals.get('dinner', '')}")
        
        # Add stops
        stops = item.get("stops", [])
        for idx, stop in enumerate(stops, 1):
            s_name = stop.get("name", "Stop")
            s_notes = stop.get("notes", "")
            s_weather = stop.get("weather", {})
            w_str = f"{s_weather.get('icon', '')} {s_weather.get('temperature', '25C')} {s_weather.get('status', '')}"
            lines.append(f"  * Stop {idx}: {s_name} ({w_str})")
            lines.append(f"    Desc: {s_notes}")
            
        # Add transit
        transit = item.get("transit_segment", {})
        t_dist = transit.get("distance_km", 0)
        t_time = transit.get("duration_minutes", 0)
        lines.append(f"  * Transit: Drive {t_dist} km (~{t_time} mins)")
        
    lines.append("----------------------------------------------------------------")
    lines.append("Generated by Smartyatra AI Planner Platform.")
    
    # Build PDF byte structures
    header = b"%PDF-1.4\n"
    offsets = []
    body = b""
    
    # Catalog
    offsets.append(len(header) + len(body))
    body += b"1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n"
    
    # Pages Tree
    offsets.append(len(header) + len(body))
    body += b"2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n"
    
    # Page
    offsets.append(len(header) + len(body))
    body += b"3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 5 0 R /Resources << /Font << /F1 4 0 R >> >> >>\nendobj\n"
    
    # Font
    offsets.append(len(header) + len(body))
    body += b"4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n"
    
    # Content text generation (page content formatting)
    text_content = f"BT\n/F1 14 Tf\n50 740 Td\n({dest.upper()} TRAVEL PLANNER) Tj\n/F1 9 Tf\n0 -20 Td\n"
    
    # Standard PDF Helvetica line spacing
    for line in lines:
        safe_line = line.replace("(", "\\(").replace(")", "\\)")
        text_content += f"({safe_line}) Tj\nT*\n"
        
    text_content += "ET"
    content_bytes = text_content.encode("utf-8")
    
    # Content stream object
    offsets.append(len(header) + len(body))
    body += f"5 0 obj\n<< /Length {len(content_bytes)} >>\nstream\n".encode("ascii")
    body += content_bytes
    body += b"\nendstream\nendobj\n"
    
    xref_start = len(header) + len(body)
    
    # Xref Table
    xref = f"xref\n0 6\n0000000000 65535 f\n".encode("ascii")
    for offset in offsets:
        xref += f"{offset:010d} 00000 n\n".encode("ascii")
        
    trailer = f"trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n{xref_start}\n%%EOF\n".encode("ascii")
    
    return header + body + xref + trailer
