"""add route table

Revision ID: 205a083bdc38
Revises: c63da83176b6
Create Date: 2026-07-16 20:13:37.080480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '205a083bdc38'
down_revision: Union[str, Sequence[str], None] = 'c63da83176b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('total_distance', sa.Float(), nullable=False))
    op.add_column('routes', sa.Column('estimated_duration', sa.Float(), nullable=False))
    op.add_column('routes', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('routes', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('routes_trip_id_fkey'), 'routes', type_='foreignkey')
    op.create_foreign_key(None, 'routes', 'trips', ['trip_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.create_foreign_key(op.f('routes_trip_id_fkey'), 'routes', 'trips', ['trip_id'], ['id'], ondelete='CASCADE')
    op.drop_column('routes', 'updated_at')
    op.drop_column('routes', 'created_at')
    op.drop_column('routes', 'estimated_duration')
    op.drop_column('routes', 'total_distance')
    # ### end Alembic commands ###
