"""add itinerary table

Revision ID: c63da83176b6
Revises: e9f344424167
Create Date: 2026-07-16 20:02:31.509173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c63da83176b6'
down_revision: Union[str, Sequence[str], None] = 'e9f344424167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('city_id', sa.Integer(), nullable=False))
    op.add_column('trips', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'trips', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_column('trips', 'updated_at')
    op.drop_column('trips', 'city_id')
    # ### end Alembic commands ###
