"""add destination table

Revision ID: e9f344424167
Revises: b2a478cf2872
Create Date: 2026-07-14 19:08:34.868647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9f344424167'
down_revision: Union[str, Sequence[str], None] = 'b2a478cf2872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itineraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itineraries_id'), 'itineraries', ['id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('start_destination_id', sa.Integer(), nullable=False),
    sa.Column('end_destination_id', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('travel_mode', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['end_destination_id'], ['destinations.id'], ),
    sa.ForeignKeyConstraint(['start_destination_id'], ['destinations.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_unique_constraint('uq_city', 'cities', ['name', 'state', 'country'])
    op.add_column('destinations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('destinations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('destinations', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('destinations', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('destinations', 'estimated_cost')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destinations', sa.Column('estimated_cost', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('destinations', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('destinations', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('destinations', 'updated_at')
    op.drop_column('destinations', 'created_at')
    op.drop_constraint('uq_city', 'cities', type_='unique')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_itineraries_id'), table_name='itineraries')
    op.drop_table('itineraries')
    # ### end Alembic commands ###
